Backup: alpha

diff --git a/dotfiles/bin/backup b/dotfiles/bin/backup
--- a/dotfiles/bin/backup
+++ b/dotfiles/bin/backup
@@ -5,10 +5,9 @@
 # Add regular backup into user crontab
 #
 # Usage:
-#	backup
+#   backup
 #   backup --init
 #   backup --cron <hourly|daily|weekly|monthly>
-#	backup --force
 #
 # Author: Alexander Burtsev, http://burtsev.me
 # License: MIT
@@ -16,13 +15,17 @@
 # 
 # Acknowledgements: Artem Sapegin, https://github.com/sapegin/dotfiles
 #
+# Links:
+#   http://www.webdav.org/specs/rfc2518.html
+#
 
 # Common stuff
 RED="$(tput setaf 1)"
 CYAN="$(tput setaf 6)"
 UNDERLINE="$(tput sgr 0 1)"
 NOCOLOR="$(tput sgr0)"
-function header() { echo -e "$UNDERLINE$CYAN$1$NOCOLOR\n"; }
+
+function header() { echo -e "$UNDERLINE$CYAN$1$NOCOLOR"; }
 function error() { echo -e "$UNDERLINE$RED$1$NOCOLOR\n"; }
 
 function usage() {
@@ -30,30 +33,72 @@ function usage() {
 	echo "  `basename $0`"
 	echo "  `basename $0` --init"
 	echo "  `basename $0` --cron <hourly|daily|weekly|monthly>"
-	echo "  `basename $0` --force"
 	echo
 }
 
+function create_webdav_config() {
+	header "Create webdav config for remote saving"
+	read -p "Webdav host (default: https://webdav.yandex.ru/): " webdav_host
+	read -p "Webdav user: " webdav_user
+	read -p "Webdav password: " -s webdav_password
+	echo
+
+	webdav_host=${webdav_host:-https://webdav.yandex.ru/}
+
+	touch $webdav_config
+	echo "webdav_host=$webdav_host" >> $webdav_config
+	echo "webdav_user=$webdav_user" >> $webdav_config
+	echo "webdav_password=$webdav_password" >> $webdav_config
+}
+
+function save_archive() {
+	if [ ! -f $webdav_config ]; then
+		exit 1
+	fi
+
+	header "Saving to remote host."
+	source $webdav_config
+	curl --user $webdav_user":"$webdav_password --request MKCOL $webdav_host"backup/" >/dev/null 2>&1
+	curl --user $webdav_user":"$webdav_password --request MKCOL $webdav_host"backup/"$wd_name >/dev/null 2>&1
+	curl --user $webdav_user":"$webdav_password -T "$1" $webdav_host"backup/"$wd_name"/" || {
+		error "Saving error."
+		exit 1
+	}
+
+	rm $1
+}
+
+# Archive & config names
+wd_name=${PWD##*/}
+webdav_config=~/.webdav
+archive_suffix=`date "+%Y-%m-%d-%H-%M-%S"`
+archive_name=$wd_name"_"$archive_suffix".tar.gz"
+
 # Create config file
 if [ "$1" == "--init" ]; then
-	# todo: create config file
-	echo ""
+	if [ ! -f $webdav_config ]; then
+		create_webdav_config
+	fi
 
 # Add backup into user crontab
 elif [ "$1" == "--cron" ]; then
 	# todo: add backup into user crontab
-	echo ""
+	echo
 
 # Create backup
 else
-	if [ -f backup_config.sh ]; then
-		echo "Config exists"
-		# http://stackoverflow.com/questions/5228345/bash-script-how-to-reference-a-file-for-variables
+	if [ ! -f $webdav_config ]; then
+		header "Webdav config for remote saving doesn’t exist. Try: `basename $0` --init\n"
+	fi
 
-	elif [ "$1" == "--force" ]; then
-		echo "Force creating archive"
+	if [ -f .backup_config ]; then
+		echo "Config exists"
+
 	else
-		error "Config file does't exists, try with --init";
-		usage
+		header "Creating an archive"
+		tar -cz --file="$archive_name" -C .. "$wd_name" 2>/dev/null
+		echo -e "Archive saved.\n"
+		save_archive $archive_name
+		echo "Done."
 	fi
 fi
