Backup: saving MySQL-dump

diff --git a/dotfiles/bin/backup b/dotfiles/bin/backup
--- a/dotfiles/bin/backup
+++ b/dotfiles/bin/backup
@@ -70,7 +70,8 @@ function create_backup_config() {
 			read -p "MySQL host (default: localhost): " mysql_host
 			read -p "MySQL database name: " mysql_dbname
 			read -p "MySQL user: " mysql_user
-			read -p "MySQL password: " mysql_password
+			read -p "MySQL password: " -s mysql_password
+			echo
 			read -p "MySQL port (default: 3306): " mysql_port
 
 			mysql_host=${mysql_host:-localhost}
@@ -92,14 +93,17 @@ function create_backup_config() {
 
 function save_archive() {
 	if [ ! -f $webdav_config ]; then
-		exit 1
+		exit
 	fi
 
-	header "Saving to remote host."
+	header "$3"
 	source $webdav_config
-	curl --user $webdav_user":"$webdav_password --request MKCOL $webdav_host"backup/" >/dev/null 2>&1
-	curl --user $webdav_user":"$webdav_password --request MKCOL $webdav_host"backup/"$1 >/dev/null 2>&1
-	error_text=`curl -s --user $webdav_user":"$webdav_password -T "$2" $webdav_host"backup/"$1"/"`
+	backup_dir=$webdav_host"backup/"
+	dest_dir=$backup_dir$1"/"
+
+	curl --user $webdav_user":"$webdav_password --request MKCOL $backup_dir >/dev/null 2>&1
+	curl --user $webdav_user":"$webdav_password --request MKCOL $dest_dir >/dev/null 2>&1
+	error_text=`curl -s --user $webdav_user":"$webdav_password -T "$2" "$dest_dir"`
 
 	if [ "$error_text" != "" ]; then
 		error "ERROR: $error_text"
@@ -112,8 +116,8 @@ function save_archive() {
 # Archive & config names
 wd_name=${PWD##*/}
 webdav_config=~/.webdav
-backup_config=.backup_config
-archive_suffix=`date "+%Y-%m-%d-%H-%M-%S"`
+backup_config=.backup
+archive_suffix=`date "+%Y-%m-%d-%H%M%S"`
 
 # Create config file for remote saving
 if [ "$1" == "--init" ]; then
@@ -146,9 +150,20 @@ else
 		source $backup_config
 		archive_name=$backup_name"_"$archive_suffix".tar.gz"
 
-		if [ $mysql_host ]; then
-			:
-			# todo: mysql dump
+		if [ $mysql_host ] && [ $mysql_dbname ]; then
+			command -v mysqldump >/dev/null 2>&1 || {
+				error "ERROR: command 'mysqldump' not found"
+				exit 1
+			}
+
+			dump_name=$mysql_dbname"_"$archive_suffix".sql"
+			dump_archive_name=$dump_name".tar.gz"
+
+			mysqldump -c -h $mysql_host -P $mysql_port -u $mysql_user --password=$mysql_password $mysql_dbname > $dump_name
+			tar czf $dump_archive_name $dump_name
+			rm $dump_name
+			save_archive $backup_name $dump_archive_name "Saving dump to remote host."
+			echo -e "Dump saved.\n"
 		fi
 
 	else
@@ -158,7 +173,7 @@ else
 	fi
 
 	tar -cz --file="$archive_name" -C .. "$wd_name" 2>/dev/null
+	save_archive $backup_name $archive_name "Saving archive to remote host."
 	echo -e "Archive saved.\n"
-	save_archive $backup_name $archive_name 
 	echo "Done."
 fi
